name: 🐳 Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    name: 🐳 Build and Push Docker Image
    env:
      DOCKER_BUILDKIT: 1
      LS_RELEASE_TAG: "v4.8.4"
      LS_CONTAINER_IMAGE_RELEASE_TAG: "4.8.4-r1"

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
      
      - name: Compute build metadata
        id: meta
        run: |
          echo "created=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_OUTPUT
          echo "version=$LS_CONTAINER_IMAGE_RELEASE_TAG" >> $GITHUB_OUTPUT

      - name: 💿 Download linkstack release
        uses: robinraju/release-downloader@v1.11
        with:
          repository: "LinkStackOrg/LinkStack"
          tag: "${{ env.LS_RELEASE_TAG }}"
          fileName: "linkstack.zip"
          tarBall: false
          zipBall: false
          extract: true
      
      - name: 🎯 Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: 🖥 Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: 🔓 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "${{ vars.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      
      - name: 🌐 Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: "linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7"
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/linkstack:${{ steps.meta.outputs.version }}
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            VCS_REF=${{ github.sha }}
            CREATED=${{ steps.meta.outputs.created }}
